export const routes = {
  ACCESSIBILITY: '/accessibility',
  LANDING: '/',
  LOGIN: '/login',
  HOME: '/home',
  REGISTER: '/registrations',
  REGISTER_UNIT_OF_MEASURE: '/registrations/unit_of_measure',
  REGISTER_CARRIER: '/registrations/carrier',
  FORM_CARRIER: '/registrations/form_carrier/:id',
  REGISTER_PRODUCT: '/registrations/product',
  FORM_PRODUCT: '/registrations/product/:id',
  REGISTER_MANUFACTURER: '/registrations/manufacturer',
  PRODUCT_GROUP: '/registrations/product_group',
  SUPPLIER_NEW: "/registrations/supplier/new",
  SUPPLIER_EDIT: "/registrations/supplier/:id",
  SUPPLIER: '/registrations/supplier',
  REGISTER_PRODUCT_TYPE: '/registrations/product_type',
}
